# Generated by Django 2.2.7 on 2019-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191123_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating_user',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
