# Generated by Django 2.2.7 on 2019-11-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_best_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='best_answer',
        ),
    ]
