# Generated by Django 2.1.3 on 2018-12-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20181227_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablelanguage',
            options={'ordering': ['lang']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to=None,
        ),
    ]
