# Generated by Django 2.1.3 on 2018-12-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20181227_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
