# Generated by Django 2.1.3 on 2018-12-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelanguage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='language/'),
        ),
    ]
