# Generated by Django 2.1.3 on 2018-12-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_availablelanguage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.AddField(
            model_name='availablelanguage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
