# Generated by Django 2.1.3 on 2018-12-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20181231_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelanguage',
            name='lang',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
