# Generated by Django 2.1.3 on 2019-01-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20190101_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelanguage',
            name='lang_code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
