# Generated by Django 2.1.3 on 2019-01-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_availablelanguage_lang_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelanguage',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ady', 'Адыгабзэ'), ('de', 'Deutsch'), ('pl', 'Polski')], default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='availablelanguage',
            name='lang_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
