# Generated by Django 2.1.3 on 2019-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20190105_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablelanguage',
            name='lg',
            field=models.CharField(blank=True, default='English', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='availablelanguage',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ady', 'Адыгабзэ'), ('de', 'Deutsch'), ('pl', 'Polski')], max_length=50, unique=True),
        ),
    ]
