# Generated by Django 2.1.3 on 2019-01-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_remove_availablelanguage_lg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelanguage',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ady', 'Адыгабзэ')], max_length=50, unique=True),
        ),
    ]
