# Generated by Django 2.1.3 on 2019-01-12 14:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20190109_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelanguage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='language/'),
        ),
    ]
