# Generated by Django 2.2.7 on 2019-11-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_auto_20190112_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
