# Generated by Django 2.2.7 on 2019-11-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190104_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='best_answer',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
