# Generated by Django 2.2.7 on 2019-11-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_best_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='best_answer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
