# Generated by Django 2.1.3 on 2018-12-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socials',
            options={'verbose_name': 'Социальные сети', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
