# Generated by Django 2.1.3 on 2019-01-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181221_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socials',
        ),
    ]
